import LocalInterface from "../localInterface";

export const english: LocalInterface = {
    addDiscussionButtonText: "Add Discussion",
    status1: "closed",
    status2: "open",
    docType3: "Discussion",
    docType4: "Meeting Summary",
    docType5: "Wiki",
    docType6: "Demo",
    docTypeDescriptor: "Type",
    docTypeFieldName: "Type",
    subjectFieldName: "Subject",
    labelsFieldName: "labels",
    descriptionFieldName: "description",
    privateFieldName: "Private",
    usersFieldName: "Users",
    submitButtonText: "Post",
    cancelButtonText: "Cancel",
    private: "Private",
    public: "Public",
    newLabelText: "New Label",
    selectLabels: "Select labels",
    deleteDocType: "Delete",
    deleteComment: "Delete",
    editComment: "Edit",
    quoteComment: "Quote",
    pinComment: "Pin",
    unpinComment: "unpin",
    updateCommentButtonText: "update",
    markdownPlaceHolder: "Message",
    selectUsers: "Select users",
    noDocSelectText: "Start a discussion or just select your relevant doc!",
    noDocSelectedButtonText: "Start a new discussion",
    menuInboxText: "Inbox",
    menuPrivateText: "Private",
    menuShortcutsText: "Shortcuts",
    menuShortcutManageText: "Manage",
    menuDashboardsText: "Dashboards",
    menuDocsText: "Search",
    menuTeamsText: "Teams",
    menuMilestonesText: "Milestones",
    MenuSettingsText: "Settings",
    docsNoResults: "No results, please try another search criteria",
    login: "login",
    logout: "logout"
}