import LocalInterface from "../localInterface";

export const hebrew: LocalInterface = {
    addDiscussionButtonText: "שיחה חדשה",
    status1: "פתוח",
    status2: "סגור",
    docType3: "דיון",
    docType4: "תקציר  פגישה",
    docType5: "Wiki",
    docType6: "דמו",
    docTypeDescriptor: "סוג",
    docTypeFieldName: "סוג",
    subjectFieldName: "נושא",
    labelsFieldName: "תוויות",
    descriptionFieldName: "תוכן",
    privateFieldName: "פרטי",
    usersFieldName: "משתמשים",
    submitButtonText: "שלח",
    cancelButtonText: "בטל",
    private: "פרטי",
    public: "ציבורי",
    newLabelText: "הוסף תווית",
    selectLabels: "בחר תוויות",
    deleteDocType: "מחק",
    deleteComment: "מחק",
    editComment: "ערוך",
    quoteComment: "צטט",
    pinComment: "נעץ",
    unpinComment: "בטל נעיצה",
    updateCommentButtonText: "עדכן",
    markdownPlaceHolder: "הודעה",
    selectUsers: "בחר משתמשים",
    noDocSelectText: "התחל דיון או בחר פריט מהרשימה",
    noDocSelectedButtonText: "הוסף דיון חדש",
    menuInboxText: "תיבת דואר",
    menuPrivateText: "פרטיות",
    menuShortcutsText: "קיצור דרך",
    menuShortcutManageText: "נהל",
    menuDashboardsText: "דוחות",
    menuDocsText: "חיפוש",
    menuTeamsText: "צוותים",
    menuMilestonesText: "ציוני דרך",
    MenuSettingsText: "הגדרות",
    docsNoResults: "לא נמצאו תוצאות, אנא שנה את תנאי החיפוש",
    login: "התחבר",
    logout: "התנתק"
}